"use client";

import { AlertCircle, CheckCircle2, Clock3, Copy, FileSpreadsheet, Loader2, PlugZap, RotateCcw, ShoppingBag, UploadCloud } from "lucide-react";
import { BillingClient } from "@/app/(authenticated)/billing/billing-client";
import { SettingsClient } from "@/app/(authenticated)/settings/settings-client";
import { useLanguage } from "@/components/providers/language-provider";

export type Phase3State = "default" | "unverified" | "sending" | "success" | "error" | "inactive" | "starter" | "growth" | "business" | "yearly" | "checkout" | "verify_error" | "before_install" | "waiting" | "connected" | "disconnected" | "reconnect" | "partial" | "files" | "invalid" | "processing" | "warning" | "complete";

const limits = { maxStores: 3, maxReportsPerMonth: 200, aiInsights: true, apiAccess: false };
const subscription = { ok: true, planId: "growth" as const, status: "active", startedAt: 1725148800000, expiresAt: 1788220800000, isActiveNow: true, cancelAtPeriodEnd: false, limits };
const user = { id: "qa-user", email: "owner@isaudi.ai", plan: "growth", planExpiresAt: 1788220800000, createdAt: 1700000000000 };

export function Phase3Preview({ section, state }: { section: "settings" | "billing" | "connections"; state: Phase3State }) {
  const { lang } = useLanguage();
  if (section === "settings") return <SettingsClient userEmail={user.email} emailVerified={state !== "unverified"} plan="growth" planExpiresAt={user.planExpiresAt} subscription={state === "inactive" ? { ...subscription, isActiveNow: false, status: "expired" } : subscription} previewState={(state === "default" ? "default" : state) as "default"} />;
  if (section === "billing") return <BillingClient user={user} subscription={subscription} previewState={(state === "default" ? "growth" : state) as "growth"} />;
  return <ConnectionsPreview state={state} lang={lang} />;
}

function ConnectionsPreview({ state, lang }: { state: Phase3State; lang: "ar" | "en" }) {
  const csv = ["files", "invalid", "processing", "warning", "complete"].includes(state);
  if (csv) return <CsvPreview state={state} lang={lang} />;
  const copy = lang === "ar" ? {
    title: "ربط متجر سلة", desc: "اربط متجرك بأمان عبر رمز ربط مخصص وقابل للاستخدام مرة واحدة.", install: "تثبيت تطبيق iSaudi.ai من سلة", connected: "متجرك متصل بسلة", waiting: "في انتظار إدخال رمز الربط في سلة", disconnected: "تم إلغاء تثبيت التطبيق", reconnect: "يلزم إعادة الربط بأمان", test: "اختبار الاتصال",
  } : { title: "Connect Salla store", desc: "Connect securely with a dedicated, single-use linking code.", install: "Install iSaudi.ai from Salla", connected: "Your store is connected to Salla", waiting: "Waiting for the link code in Salla", disconnected: "The app was uninstalled", reconnect: "Secure reconnection is required", test: "Test connection" };
  const effective = state === "default" ? "before_install" : state;
  const status = effective === "connected" || effective === "partial" ? copy.connected : effective === "waiting" ? copy.waiting : effective === "disconnected" ? copy.disconnected : effective === "reconnect" ? copy.reconnect : (lang === "ar" ? "لم يتم تثبيت التطبيق بعد" : "The app is not installed yet");
  return <div className="mx-auto max-w-2xl"><section className="relative overflow-hidden rounded-3xl border border-white/10 bg-[#0e1218] p-6 text-center shadow-2xl sm:p-8"><div className="absolute inset-x-0 top-0 h-px bg-gradient-to-r from-transparent via-[#0fc9a7] to-transparent" /><span className="mx-auto mb-5 grid h-16 w-16 place-items-center rounded-2xl border border-[#0fc9a7]/20 bg-[#0fc9a7]/10 text-[#0fc9a7]"><ShoppingBag className="h-8 w-8" /></span><h1 className="text-3xl font-bold text-white">{copy.title}</h1><p className="mx-auto mt-3 max-w-lg leading-7 text-[#94a3b8]">{copy.desc}</p><div className="mt-6 flex items-center justify-center gap-2 rounded-xl border border-white/10 bg-[#161c24] p-4 text-sm text-[#b7c0cd]">{effective === "connected" || effective === "partial" ? <CheckCircle2 className="h-5 w-5 text-[#0fc9a7]" /> : effective === "waiting" ? <Clock3 className="h-5 w-5 text-[#e6b95c]" /> : effective === "reconnect" ? <RotateCcw className="h-5 w-5 text-[#e6b95c]" /> : <PlugZap className="h-5 w-5 text-[#94a3b8]" />}{status}</div>{effective === "waiting" && <div className="mt-5 rounded-2xl border border-[#e6b95c]/20 bg-[#161c24] p-5"><p className="text-xs uppercase tracking-widest text-[#64748b]">{lang === "ar" ? "رمز الربط" : "Link code"}</p><div className="mt-3 flex items-center justify-center gap-3"><strong className="font-mono text-2xl tracking-[.18em] text-[#e6b95c]">A8F2-91BC-72D4-10EE</strong><Copy className="h-5 w-5 text-[#94a3b8]" /></div><p className="mt-3 text-sm text-[#94a3b8]">09:42</p></div>}{effective === "partial" && <div className="mt-5 rounded-xl border border-red-400/20 bg-red-400/10 p-4 text-start text-red-300"><div className="flex gap-2"><AlertCircle className="h-5 w-5 shrink-0" /><span>{lang === "ar" ? "تم الاتصال، لكن تعذر التحقق من قراءة الطلبات." : "Connected, but order read access could not be verified."}</span></div></div>}<button className={`mt-6 min-h-12 w-full rounded-xl font-bold ${effective === "connected" || effective === "partial" ? "border border-[#0fc9a7]/30 bg-[#0fc9a7]/5 text-[#72ead4]" : "bg-[#e6b95c] text-[#06090c]"}`}>{effective === "connected" || effective === "partial" ? copy.test : effective === "reconnect" || effective === "disconnected" ? copy.reconnect : copy.install}</button></section></div>;
}

function CsvPreview({ state, lang }: { state: Phase3State; lang: "ar" | "en" }) {
  const selected = state !== "invalid";
  const message = state === "invalid" ? (lang === "ar" ? "يجب اختيار ملف CSV صالح." : "Choose a valid CSV file.") : state === "warning" ? (lang === "ar" ? "تم تخطي صفين لعدم اكتمال البيانات." : "Two incomplete rows were skipped.") : state === "complete" ? (lang === "ar" ? "اكتمل التحليل وسيتم تحويلك للوحة التحكم." : "Analysis is complete; redirecting to your dashboard.") : null;
  return <div className="mx-auto max-w-3xl"><section className="relative overflow-hidden rounded-3xl border border-white/10 bg-[#0e1218] p-6 shadow-2xl sm:p-8"><div className="absolute inset-x-0 top-0 h-px bg-gradient-to-r from-transparent via-[#e6b95c] to-transparent" /><div className="text-center"><span className="mx-auto mb-4 grid h-16 w-16 place-items-center rounded-2xl border border-[#e6b95c]/20 bg-[#e6b95c]/10 text-[#e6b95c]"><FileSpreadsheet className="h-8 w-8" /></span><h1 className="text-3xl font-bold text-white">{lang === "ar" ? "رفع البيانات يدويًا" : "Import CSV data"}</h1><p className="mt-2 text-[#94a3b8]">{lang === "ar" ? "ملفا المنتجات والطلبات مطلوبان." : "Both product and order files are required."}</p></div>{message && <div className={`mt-6 rounded-xl border p-4 text-sm ${state === "invalid" ? "border-red-400/20 bg-red-400/10 text-red-300" : state === "warning" ? "border-[#e6b95c]/20 bg-[#e6b95c]/10 text-[#f4d58d]" : "border-[#0fc9a7]/20 bg-[#0fc9a7]/10 text-[#72ead4]"}`}>{message}</div>}<div className="mt-6 grid gap-4 sm:grid-cols-2">{[lang === "ar" ? "ملف المنتجات" : "Products file", lang === "ar" ? "ملف الطلبات" : "Orders file"].map((label, i) => <div key={label} className="rounded-2xl border border-dashed border-white/15 bg-[#161c24] p-5"><UploadCloud className="mb-3 h-7 w-7 text-[#e6b95c]" /><h2 className="font-bold text-white">{label}</h2><p className="mt-2 truncate text-xs text-[#64748b]">{selected ? (i ? "orders.csv · 82 KB" : "products.csv · 46 KB") : (lang === "ar" ? "لم يتم اختيار ملف" : "No file selected")}</p></div>)}</div><button className="mt-6 flex min-h-12 w-full items-center justify-center gap-2 rounded-xl bg-[#e6b95c] font-bold text-[#06090c]">{state === "processing" && <Loader2 className="h-5 w-5 animate-spin" />}{state === "processing" ? (lang === "ar" ? "جاري المعالجة..." : "Processing…") : (lang === "ar" ? "تشغيل التحليل" : "Run analysis")}</button></section></div>;
}
