'use client';

import Image from 'next/image';
import { FormEvent, useCallback, useEffect, useLayoutEffect, useMemo, useState } from 'react';
import { useRouter } from 'next/navigation';
import { BarChart3, CreditCard, FileText, Link2, LogOut, Menu, Settings, ShieldCheck, Users, Video, X } from 'lucide-react';
import { AdminVideoManager } from './video-manager';

type Lang = 'ar' | 'en';
type PortalData = { admin: { email: string; role: string }; overview: Record<string, number>; users: Record<string, unknown>[]; subscriptions: Record<string, unknown>[]; payments: Record<string, unknown>[]; connections: Record<string, unknown>[]; reports: Record<string, unknown>[]; audit: Record<string, unknown>[] };
type BootstrapState = { authenticated: boolean; setupAvailable: boolean; databaseUnavailable?: boolean; data: PortalData | null };
const text = {
  ar: { brand: 'لوحة الإدارة', overview: 'نظرة عامة', users: 'المستخدمون', subscriptions: 'الاشتراكات', payments: 'المدفوعات', connections: 'الاتصالات', reports: 'التقارير واستخدام AI', audit: 'سجل التدقيق', settings: 'الإعدادات', video: 'فيديو كيف يعمل', logout: 'تسجيل الخروج', loading: 'جارٍ التحميل…', empty: 'لا توجد بيانات', login: 'تسجيل دخول الإدارة', setup: 'الإعداد الأول للمدير الأعلى', email: 'البريد الإلكتروني', password: 'كلمة المرور', signIn: 'تسجيل الدخول', forgot: 'نسيت كلمة المرور؟', send: 'إرسال رابط الاستعادة', create: 'إنشاء حساب الإدارة', independent: 'كلمة مرور إدارية مستقلة (14 حرفاً على الأقل)', reset: 'إعادة تعيين كلمة المرور', save: 'حفظ كلمة المرور', newPassword: 'كلمة المرور الجديدة (14 حرفاً على الأقل)', transferConfirm: 'تأكيد نقل الإدارة', code: 'رمز التأكيد المرسل للبريد', success: 'تمت العملية بنجاح', busy: 'جارٍ التنفيذ…', db: 'قاعدة البيانات المحلية غير متاحة حالياً. ستعمل العمليات بعد ربط D1.', normalLogin: 'يلزم تسجيل الدخول أولاً بالحساب العادي الموثق والمخوّل.', changePassword: 'تغيير كلمة المرور', currentPassword: 'كلمة المرور الحالية', nextPassword: 'كلمة المرور الجديدة', transfer: 'نقل صلاحية المدير الأعلى', transferHelp: 'لن يكتمل النقل إلا بعد تحقق البريد المستهدف.', targetEmail: 'البريد الإلكتروني المستهدف', transferSend: 'إرسال طلب النقل' },
  en: { brand: 'Admin Console', overview: 'Overview', users: 'Users', subscriptions: 'Subscriptions', payments: 'Payments', connections: 'Connections', reports: 'Reports & AI usage', audit: 'Audit log', settings: 'Settings', video: 'How It Works Video', logout: 'Sign out', loading: 'Loading…', empty: 'No data available', login: 'Admin sign in', setup: 'Super admin setup', email: 'Email address', password: 'Password', signIn: 'Sign in', forgot: 'Forgot password?', send: 'Send recovery link', create: 'Create admin account', independent: 'Independent admin password (14 characters minimum)', reset: 'Reset password', save: 'Save password', newPassword: 'New password (14 characters minimum)', transferConfirm: 'Confirm admin transfer', code: 'Email verification code', success: 'Completed successfully', busy: 'Working…', db: 'The local database is unavailable. Actions will work when D1 is connected.', normalLogin: 'First sign in with the verified, authorized customer account.', changePassword: 'Change password', currentPassword: 'Current password', nextPassword: 'New password', transfer: 'Transfer super admin role', transferHelp: 'The transfer completes only after the target email is verified.', targetEmail: 'Target email', transferSend: 'Send transfer request' },
};
const tabs = [['overview', BarChart3], ['users', Users], ['subscriptions', ShieldCheck], ['payments', CreditCard], ['connections', Link2], ['reports', FileText], ['audit', ShieldCheck], ['video', Video], ['settings', Settings]] as const;

async function api(action: string, payload?: Record<string, unknown>) { const response = await fetch(`/admin/api/${action}`, { method: payload ? 'POST' : 'GET', credentials: 'same-origin', headers: payload ? { 'Content-Type': 'application/json' } : undefined, body: payload ? JSON.stringify(payload) : undefined, cache: 'no-store' }); const result = await response.json(); if (!response.ok) throw new Error(result.error || 'Request failed'); return result; }
function Field({ label, name, type = 'text' }: { label: string; name: string; type?: string }) { return <label className="block text-sm font-medium text-slate-300">{label}<input name={name} type={type} required className="mt-2 min-h-12 w-full rounded-xl border border-white/10 bg-white/5 px-4 text-white outline-none transition focus:border-[#d7b568]/60" /></label>; }
function FormBox({ children, onSubmit, button, lang }: { children: React.ReactNode; onSubmit: (data: FormData) => Promise<void>; button: string; lang: Lang }) { const [error, setError] = useState(''); const [done, setDone] = useState(''); const [busy, setBusy] = useState(false); return <form className="space-y-4 rounded-3xl border border-white/10 bg-[#0d151d] p-6 shadow-2xl shadow-black/20" onSubmit={async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setBusy(true); setError(''); setDone(''); try { await onSubmit(new FormData(event.currentTarget)); setDone(text[lang].success); } catch (e) { setError(e instanceof Error ? e.message : 'Request failed'); } finally { setBusy(false); } }}>{children}{error && <p role="alert" className="text-sm text-red-300">{error}</p>}{done && <p className="text-sm text-teal-300">{done}</p>}<button disabled={busy} className="min-h-12 w-full rounded-xl bg-[#d7b568] px-4 font-semibold text-[#071018] transition hover:bg-[#ecd08a] disabled:opacity-50">{busy ? text[lang].busy : button}</button></form>; }
function DataTable({ rows, lang }: { rows: Record<string, unknown>[]; lang: Lang }) { if (!rows.length) return <div className="rounded-3xl border border-white/10 bg-[#0d151d] p-10 text-center text-slate-400">{text[lang].empty}</div>; const columns = Object.keys(rows[0]).filter(key => !key.includes('json')); return <div className="overflow-x-auto rounded-3xl border border-white/10 bg-[#0d151d]"><table className="min-w-full text-sm"><thead className="bg-white/[.035]"><tr>{columns.map(column => <th key={column} className="whitespace-nowrap px-5 py-4 text-start text-xs uppercase tracking-wider text-slate-500">{column}</th>)}</tr></thead><tbody>{rows.map((row, index) => <tr key={String(row.id ?? index)} className="border-t border-white/[.07]">{columns.map(column => <td key={column} className="whitespace-nowrap px-5 py-4 text-slate-300">{column.includes('At') || column.includes('_at') ? (row[column] ? new Date(Number(row[column])).toLocaleString(lang === 'ar' ? 'ar-SA' : 'en-US') : '—') : String(row[column] ?? '—')}</td>)}</tr>)}</tbody></table></div>; }

function SectionTable({ section, lang }: { section: string; lang: Lang }) {
  const [page, setPage] = useState(1);
  const [draft, setDraft] = useState('');
  const [search, setSearch] = useState('');
  const requestKey = `${section}:${page}:${search}`;
  const [result, setResult] = useState<{ key: string; rows: Record<string, unknown>[]; hasMore: boolean; error: string }>({ key: '', rows: [], hasMore: false, error: '' });
  const loading = result.key !== requestKey;
  useEffect(() => {
    let active = true;
    const query = new URLSearchParams({ section, page: String(page), pageSize: '25' });
    if (search) query.set('search', search);
    void api(`section?${query}`).then(response => { if (active) setResult({ key: requestKey, rows: response.rows, hasMore: response.hasMore, error: '' }); }).catch(cause => { if (active) setResult({ key: requestKey, rows: [], hasMore: false, error: cause instanceof Error ? cause.message : 'Request failed' }); });
    return () => { active = false; };
  }, [page, requestKey, search, section]);
  return <div className="space-y-4"><form className="flex gap-2" onSubmit={(event) => { event.preventDefault(); setPage(1); setSearch(draft.trim()); }}><input value={draft} onChange={event => setDraft(event.target.value)} maxLength={100} placeholder={lang === 'ar' ? 'بحث بالبريد أو الإجراء' : 'Search email or action'} className="min-h-11 min-w-0 flex-1 rounded-xl border border-white/10 bg-white/5 px-4 text-sm outline-none focus:border-[#d7b568]/60" /><button className="rounded-xl bg-white/10 px-5 text-sm font-medium hover:bg-white/15">{lang === 'ar' ? 'بحث' : 'Search'}</button></form>{loading ? <div className="rounded-3xl border border-white/10 bg-[#0d151d] p-10 text-center text-slate-400">{text[lang].loading}</div> : result.error ? <p role="alert" className="rounded-2xl border border-red-400/20 bg-red-400/10 p-4 text-sm text-red-200">{result.error}</p> : <DataTable rows={result.rows} lang={lang} />}<div className="flex items-center justify-between"><button disabled={page === 1 || loading} onClick={() => setPage(value => Math.max(1, value - 1))} className="min-h-10 rounded-xl border border-white/10 px-4 text-sm disabled:opacity-30">{lang === 'ar' ? 'السابق' : 'Previous'}</button><span className="text-sm text-slate-500">{lang === 'ar' ? 'صفحة' : 'Page'} {page}</span><button disabled={!result.hasMore || loading} onClick={() => setPage(value => value + 1)} className="min-h-10 rounded-xl border border-white/10 px-4 text-sm disabled:opacity-30">{lang === 'ar' ? 'التالي' : 'Next'}</button></div></div>;
}

export default function AdminPortal({ mode }: { mode?: 'reset' | 'transfer' }) {
  const router = useRouter(); const [lang, setLang] = useState<Lang>('ar'); const t = text[lang]; const [status, setStatus] = useState<BootstrapState | null>(null); const [data, setData] = useState<PortalData | null>(null); const [tab, setTab] = useState('overview'); const [menu, setMenu] = useState(false); const token = useMemo(() => typeof window === 'undefined' ? '' : new URLSearchParams(window.location.search).get('token') || '', []);
  const applyBootstrap = useCallback((state: BootstrapState) => { setStatus(state); setData(state.data); if (state.data && state.data.admin.role !== 'super_admin') setTab('settings'); }, []);
  const load = async () => { applyBootstrap(await api('bootstrap') as BootstrapState); };
  useLayoutEffect(() => { if (token) window.history.replaceState(null, '', window.location.pathname); }, [token]);
  useEffect(() => {
    document.documentElement.lang = lang;
    document.documentElement.dir = lang === 'ar' ? 'rtl' : 'ltr';
  }, [lang]);
  useEffect(() => { let active = true; void api('bootstrap').then(state => { if (active) applyBootstrap(state as BootstrapState); }).catch(() => active && setStatus({ authenticated: false, setupAvailable: false, data: null })); return () => { active = false; }; }, [applyBootstrap]);
  const language = <button onClick={() => setLang(lang === 'ar' ? 'en' : 'ar')} className="min-h-10 rounded-xl border border-white/10 px-4 text-sm text-slate-300 hover:bg-white/5">{lang === 'ar' ? 'English' : 'العربية'}</button>;
  if (mode === 'reset') return <Shell title={t.reset} lang={lang} language={language}><FormBox button={t.save} lang={lang} onSubmit={async form => { await api('confirm-reset', { token, password: form.get('password') }); router.replace('/admin'); }}><Field label={t.newPassword} name="password" type="password" /></FormBox></Shell>;
  if (mode === 'transfer') return <Shell title={t.transferConfirm} lang={lang} language={language}><FormBox button={t.transferConfirm} lang={lang} onSubmit={async form => { await api('confirm-transfer', { token, code: form.get('code'), password: form.get('password') }); router.replace('/admin'); }}><Field label={t.code} name="code" /><Field label={t.independent} name="password" type="password" /></FormBox></Shell>;
  if (!status) return <Shell title={t.brand} lang={lang} language={language}><p className="text-center text-slate-400">{t.loading}</p></Shell>;
  if (!status.authenticated) return <Shell title={status.setupAvailable ? t.setup : t.login} lang={lang} language={language}>{status.databaseUnavailable && <p role="alert" className="mb-5 rounded-2xl border border-amber-400/20 bg-amber-400/10 p-4 text-sm text-amber-100">{t.db}</p>}{status.setupAvailable ? <FormBox button={t.create} lang={lang} onSubmit={async form => { await api('setup', { password: form.get('password') }); await load(); }}><p className="text-sm text-slate-400">{t.normalLogin}</p><Field label={t.independent} name="password" type="password" /></FormBox> : <><FormBox button={t.signIn} lang={lang} onSubmit={async form => { await api('login', { email: form.get('email'), password: form.get('password') }); await load(); }}><Field label={t.email} name="email" type="email" /><Field label={t.password} name="password" type="password" /></FormBox><details className="mt-5 rounded-2xl border border-white/10 bg-[#0d151d] p-4 text-slate-300"><summary>{t.forgot}</summary><div className="mt-4"><FormBox button={t.send} lang={lang} onSubmit={async form => { await api('request-reset', { email: form.get('email') }); }}><Field label={t.email} name="email" type="email" /></FormBox></div></details></>}</Shell>;
  if (!data) return <Shell title={t.brand} lang={lang} language={language}><p>{t.loading}</p></Shell>;
  const available = data.admin.role === 'super_admin' ? tabs : tabs.filter(([id]) => id === 'settings');
  return <main dir={lang === 'ar' ? 'rtl' : 'ltr'} className="min-h-screen bg-[#06090c] text-white"><header className="sticky top-0 z-40 border-b border-white/10 bg-[#06090c]/90 backdrop-blur-xl"><div className="mx-auto flex min-h-20 max-w-[1500px] items-center justify-between px-4 sm:px-6"><div className="flex items-center gap-3"><button onClick={() => setMenu(!menu)} className="grid h-11 w-11 place-items-center rounded-xl border border-white/10 lg:hidden">{menu ? <X /> : <Menu />}</button><Image src="/brand/design-preview-logo.png" alt="iSaudi.ai" width={120} height={34} className="h-8 w-auto object-contain" /><span className="hidden border-s border-white/10 ps-3 text-sm text-slate-400 sm:block">{t.brand}</span></div><div className="flex gap-2">{language}<button onClick={async () => { await api('logout', {}); router.replace('/admin'); router.refresh(); }} className="inline-flex min-h-10 items-center gap-2 rounded-xl border border-white/10 px-3 text-sm text-slate-300"><LogOut className="h-4 w-4" /><span className="hidden sm:inline">{t.logout}</span></button></div></div></header><div className="mx-auto grid max-w-[1500px] lg:grid-cols-[260px_1fr]"><aside className={`${menu ? 'block' : 'hidden'} border-b border-white/10 bg-[#081017] p-4 lg:block lg:min-h-[calc(100vh-5rem)] lg:border-b-0 lg:border-e lg:p-5`}><div className="mb-5 rounded-2xl border border-white/10 bg-white/[.03] p-4"><p className="truncate text-sm font-medium">{data.admin.email}</p><p className="mt-1 text-xs uppercase tracking-wider text-teal-400">{data.admin.role.replace('_', ' ')}</p></div><nav className="grid grid-cols-2 gap-2 sm:grid-cols-3 lg:grid-cols-1">{available.map(([id, Icon]) => <button key={id} onClick={() => { setTab(id); setMenu(false); }} className={`flex min-h-11 items-center gap-3 rounded-xl px-3 text-start text-sm transition ${tab === id ? 'bg-[#d7b568] font-semibold text-[#071018]' : 'text-slate-400 hover:bg-white/5 hover:text-white'}`}><Icon className="h-4 w-4" />{t[id]}</button>)}</nav></aside><section className="min-w-0 px-4 py-7 sm:px-7 lg:px-10 lg:py-10">{tab === 'video' ? <AdminVideoManager lang={lang} /> : <><h1 className="mb-6 text-2xl font-semibold">{t[tab as keyof typeof t] ?? t.settings}</h1>{tab === 'overview' ? <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{Object.entries(data.overview).map(([key, value]) => <article key={key} className="rounded-3xl border border-white/10 bg-[#0d151d] p-6"><p className="text-sm text-slate-500">{key}</p><p className="mt-3 text-3xl font-semibold">{Number(value).toLocaleString(lang === 'ar' ? 'ar-SA' : 'en-US')}</p></article>)}</div> : tab === 'settings' ? <SettingsPanel superAdmin={data.admin.role === 'super_admin'} lang={lang} /> : <SectionTable key={tab} section={tab} lang={lang} />}</>}</section></div></main>;
}
function SettingsPanel({ superAdmin, lang }: { superAdmin: boolean; lang: Lang }) { const router = useRouter(); const t = text[lang]; return <div className="grid gap-6 xl:grid-cols-2"><FormBox button={t.changePassword} lang={lang} onSubmit={async form => { await api('change-password', { currentPassword: form.get('current'), newPassword: form.get('next') }); router.replace('/admin'); router.refresh(); }}><Field label={t.currentPassword} name="current" type="password" /><Field label={t.nextPassword} name="next" type="password" /></FormBox>{superAdmin && <FormBox button={t.transferSend} lang={lang} onSubmit={async form => { await api('request-transfer', { targetEmail: form.get('email'), currentPassword: form.get('password') }); }}><h3 className="font-semibold">{t.transfer}</h3><p className="text-sm text-amber-200">{t.transferHelp}</p><Field label={t.targetEmail} name="email" type="email" /><Field label={t.currentPassword} name="password" type="password" /></FormBox>}</div>; }
function Shell({ title, children, lang, language }: { title: string; children: React.ReactNode; lang: Lang; language: React.ReactNode }) { return <main dir={lang === 'ar' ? 'rtl' : 'ltr'} className="min-h-screen bg-[#06090c] px-4 py-10 text-white"><div className="mx-auto max-w-md"><div className="mb-8 flex items-center justify-between"><Image src="/brand/design-preview-logo.png" alt="iSaudi.ai" width={126} height={38} className="h-9 w-auto object-contain" />{language}</div><p className="mb-2 text-xs uppercase tracking-[.22em] text-[#d7b568]">Secure operations</p><h1 className="mb-6 text-2xl font-semibold">{title}</h1>{children}</div></main>; }
